apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-statefulset
spec:
  serviceName: keycloak-service
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-auth
  template:
    metadata:
      labels:
        app: keycloak-auth
    spec:
      containers:
      - name: auth-server
        image: quay.io/keycloak/keycloak:latest
        env:
        - name: REALM
          value: "production"
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak-client-secret
              key: secret
        - name: AUTH_URL
          value: "https://keycloak.example.com"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-auth-service
spec:
  selector:
    app: keycloak-auth
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secret
type: Opaque
data:
  client-id: "bXktY2xpZW50"  # Base64 encoded "my-client"
  client-secret: "cGFzc3dvcmQ="  # Base64 encoded "password"